imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "../../vendor/beberlei/doctrineextensions/config/mysql.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

doctrine_migrations:
    dir_name: "%kernel.project_dir%/src/AppBundle/Migrations"
    namespace: AppBundle\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: BY_YEAR_AND_MONTH

framework:
    #esi: ~
    translator:
        enabled: true
        logging: false
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: PHP_SESSION_MVM
        cookie_path: '%router.request_context.base_url%'
        cookie_domain: '%router.request_context.host%'
        cookie_secure: '%secure_cookies%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
        - 'NinesUtilBundle:form:fields.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
        - 'jquery.collection.html.twig'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/vendor/ubermichael/nines/UtilBundle/Resources/views': NinesUtilBundle
        '%kernel.project_dir%/vendor/ninsuo/symfony-collection': NinsuoSymfonyCollection
    globals:
        text_service: '@Nines\UtilBundle\Services\Text'
        piwik_enabled: '%dhil.piwik_enabled%'
        piwik_url: '%dhil.piwik_url%'
        piwik_siteid: '%dhil.piwik_siteid%'
        piwik_domain: '%dhil.piwik_domain%'
    date:
        format: Y-m-d, H:i:s
        interval_format: '%%d days'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: dir       # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # bootstrapy pagination
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nines\UserBundle\Entity\User
    profile:
        form:
            type: Nines\UserBundle\Form\ProfileType
    change_password:
        form:
            type: Nines\UserBundle\Form\PasswordType
    from_email:
        address: noreply@dhil.lib.sfu.ca
        sender_name: WPHP User Manager

knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig

nines_user:
    permission_levels: [ ROLE_ADMIN, ROLE_BLOG_ADMIN, ROLE_COMMENT_ADMIN, ROLE_CONTENT_ADMIN ]
